//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GamingGearEntities : DbContext
    {
        public GamingGearEntities()
            : base("name=GamingGearEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HANG> HANGs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KIEUPK> KIEUPKs { get; set; }
        public DbSet<LOAIPK> LOAIPKs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHUKIEN> PHUKIENs { get; set; }
        public DbSet<PHUKIENBAOHANH> PHUKIENBAOHANHs { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<THANHTOAN> THANHTOANs { get; set; }
    
        [EdmFunction("GamingGearEntities", "SanphamHang")]
        public virtual IQueryable<SanphamHang_Result> SanphamHang(string tenhang)
        {
            var tenhangParameter = tenhang != null ?
                new ObjectParameter("tenhang", tenhang) :
                new ObjectParameter("tenhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SanphamHang_Result>("[GamingGearEntities].[SanphamHang](@tenhang)", tenhangParameter);
        }
    
        [EdmFunction("GamingGearEntities", "TongKPK")]
        public virtual IQueryable<TongKPK_Result> TongKPK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TongKPK_Result>("[GamingGearEntities].[TongKPK]()");
        }
    
        [EdmFunction("GamingGearEntities", "TongPK")]
        public virtual IQueryable<TongPK_Result> TongPK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TongPK_Result>("[GamingGearEntities].[TongPK]()");
        }
    
        [EdmFunction("GamingGearEntities", "XEMDSPK")]
        public virtual IQueryable<XEMDSPK_Result> XEMDSPK(string maloaipk)
        {
            var maloaipkParameter = maloaipk != null ?
                new ObjectParameter("maloaipk", maloaipk) :
                new ObjectParameter("maloaipk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<XEMDSPK_Result>("[GamingGearEntities].[XEMDSPK](@maloaipk)", maloaipkParameter);
        }
    
        [EdmFunction("GamingGearEntities", "XEMPK")]
        public virtual IQueryable<XEMPK_Result> XEMPK(string mapk)
        {
            var mapkParameter = mapk != null ?
                new ObjectParameter("mapk", mapk) :
                new ObjectParameter("mapk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<XEMPK_Result>("[GamingGearEntities].[XEMPK](@mapk)", mapkParameter);
        }
    
        public virtual int DoiMatKhau(string username, string passwordcu, string passwordmoi)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordcuParameter = passwordcu != null ?
                new ObjectParameter("passwordcu", passwordcu) :
                new ObjectParameter("passwordcu", typeof(string));
    
            var passwordmoiParameter = passwordmoi != null ?
                new ObjectParameter("passwordmoi", passwordmoi) :
                new ObjectParameter("passwordmoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoiMatKhau", usernameParameter, passwordcuParameter, passwordmoiParameter);
        }
    }
}
