//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG
    {
        public HANG()
        {
            this.LOAIPKs = new HashSet<LOAIPK>();
        }
    
        public string MaHANG { get; set; }
        public string Tenhang { get; set; }
        public string Quocgia { get; set; }
    
        public virtual ICollection<LOAIPK> LOAIPKs { get; set; }
    }
}
