//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaHD { get; set; }
        public string MaTToan { get; set; }
        public string TenKH { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayxuatHD { get; set; }
        public Nullable<float> TongTienTT { get; set; }
    
        public virtual THANHTOAN THANHTOAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
