//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPK
    {
        public LOAIPK()
        {
            this.PHUKIENs = new HashSet<PHUKIEN>();
        }
    
        public string MaloaiPK { get; set; }
        public string TenloaiPK { get; set; }
        public Nullable<float> Gia { get; set; }
        public string MaHANG { get; set; }
        public Nullable<int> Thoigianbaohanh { get; set; }
        public Nullable<int> Soluongcuahang { get; set; }
        public Nullable<int> Soluongkho { get; set; }
        public string MaNCC { get; set; }
    
        public virtual HANG HANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual ICollection<PHUKIEN> PHUKIENs { get; set; }
    }
}
