//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public NHACUNGCAP()
        {
            this.LOAIPKs = new HashSet<LOAIPK>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string Diachi { get; set; }
        public string soFax { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<LOAIPK> LOAIPKs { get; set; }
    }
}
