//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUKIENBAOHANH
    {
        public string MaPK { get; set; }
        public Nullable<System.DateTime> Thoigianbaohanh { get; set; }
        public Nullable<System.DateTime> Hantra { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string SoCMND { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Ngayhoantra { get; set; }
        public Nullable<System.DateTime> Ngayhoantrathucte { get; set; }
    }
}
