//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUKIEN
    {
        public PHUKIEN()
        {
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string MaPK { get; set; }
        public string MaloaiPK { get; set; }
        public string MakieuPK { get; set; }
        public Nullable<System.DateTime> Thoigianbaohanh { get; set; }
        public Nullable<bool> TTDaban { get; set; }
        public Nullable<bool> Vitri { get; set; }
    
        public virtual KIEUPK KIEUPK { get; set; }
        public virtual LOAIPK LOAIPK { get; set; }
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
