//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMQL_CuahangPKGaming.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string MaTK { get; set; }
        public string Id { get; set; }
        public string Pw { get; set; }
        public Nullable<int> Phanquyen { get; set; }
        public string MaNV { get; set; }
    }
}
